# This is a basic workflow to help you get started with Actions

name: tv189

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  schedule:
    - cron: '0 1 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr
        python -m pip install --upgrade pip
        pip install pytesseract
        pip install pillow
        pip install requests
        pip install rsa
    - name: signin tv189
      run: |
        python ./tv189.py
    - name: signin blt
      run: |
        bash ./blt.sh
    - name: signin cloud189
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()
        IFS="#"
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$user_num;i++))
        do
        python cloud189.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done